on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: zenith.o2switch.net
        username: ydpn4730
        password: ${{ secrets.FTP_PWD }}
        server-dir: public_html/nsi/
        local-dir: ./site/
